#sudo: required
#dist: trusty

#  - pip install --user --upgrade pip
#  - pip --version

#script:
#  - bash -xve ./test/travis_ros_install.bash

language: python

python:
  - 3.3
  - 3.4

install:
  - pip install coveralls
