#sudo: required
#dist: trusty

#  - pip install --user --upgrade pip
#  - pip --version

#script:
#  - bash -xve ./test/travis_ros_install.bash

sudo: true
language: python

matrix:
  include:
    - os: linux
      python: "3.6"
      sudo: required
      env:
        - TARGET="lint"
      before_script:
        - pip3 install ufolint
        - sudo apt-get -qq update
        - sudo apt-get install -y shellcheck
      script:
  	- pip --version
